name: CI

on:
  - push
  - pull_request

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.4.2"
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build:frontend
      - name: Build backend
        run: npm run build:backend
  build-image:
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Log into GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          tags: ghcr.io/noizwaves/running:latest
      - name: Build and Push ${{ github.sha }}
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          push: true
          tags: ghcr.io/noizwaves/running:${{ github.sha }}
